import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, CalendarDays } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Chip, Page, PageHeader, Panel, SkillBar, StatCard } from "@/components/aicp/primitives";
import { api, type Event, type Internship } from "@/lib/api";
import { getCurrentStudentId, getStoredUser } from "@/lib/auth";

export const Route = createFileRoute("/")({ component: Dashboard });
function Dashboard(){
 const user=getStoredUser(); const id=getCurrentStudentId();
 const [profile,setProfile]=useState<any>(null),[skills,setSkills]=useState<any[]>([]),[recs,setRecs]=useState<Internship[]>([]),[apps,setApps]=useState<any[]>([]),[courses,setCourses]=useState<any[]>([]),[certs,setCerts]=useState<any[]>([]),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{ if(!id){setLoading(false);return;} Promise.all([api.profile(id),api.skillProfile(id),api.recommendations(id),api.applications(id),api.courses(),api.certifications(id),api.events()]).then(([p,s,r,a,c,ce,e])=>{setProfile({...p,overall:Number(s?.overall??0)});setSkills(s?.skills??[]);setRecs(r??[]);setApps(a??[]);setCourses(c??[]);setCerts(ce??[]);setEvents(e??[])}).catch(err=>toast.error(err.message)).finally(()=>setLoading(false));},[id]);
 const overall=profile?profile.overall:0;
 return <Page><PageHeader title={`Welcome back, ${String(user?.["name"]??"Student").split(" ")[0]}`} subtitle="Your career journey: assess, understand, learn, apply and showcase." />
  {loading?<p className="text-sm text-muted-foreground">Loading your dashboard…</p>:!id?<div className="rounded-lg border border-border bg-card p-6">Please <Link className="text-brass underline" to="/login">sign in</Link> to load your student data.</div>:<>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Overall Skill Score" value={String(overall)} suffix="/100" note={overall?"Based on assessed skills":"Take an assessment"}/><StatCard label="Courses" value={String(courses.length)} note="Available to you"/><StatCard label="Applications" value={String(apps.length)} note="Tracked in your account"/><StatCard label="Certifications" value={String(certs.length)} note="In your profile"/></div>
  <div className="mt-10 grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
   <Panel title="Recommended for you" action={<Link to="/internships" className="text-xs text-brass underline">View all</Link>}><ul className="divide-y divide-border">{recs.slice(0,3).map(r=><li key={r.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 p-4"><span className="grid h-10 w-10 place-items-center rounded border border-border bg-secondary font-display text-sm">{r.title.slice(0,2)}</span><span><span className="block text-sm font-medium">{r.title}</span><span className="block text-xs text-muted-foreground">{r.company} · {r.location}</span></span><span className="font-display text-xl text-success">{r.match_score}%</span></li>)}{!recs.length&&<li className="p-5 text-sm text-muted-foreground">Complete an assessment to generate recommendations.</li>}</ul></Panel>
   <Panel title="Upcoming events" action={<span className="text-xs text-muted-foreground">Calendar</span>}><ul className="divide-y divide-border">{events.slice(0,3).map(e=><li key={e.id} className="flex gap-4 p-4"><span className="shrink-0 text-center"><span className="label-caps block">{new Date(e.event_date).toLocaleString(undefined,{month:"short"})}</span><span className="block font-display text-lg">{new Date(e.event_date).getDate()}</span></span><span><span className="block text-sm font-medium">{e.title}</span><span className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3 w-3"/>{new Date(e.event_date).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</span></span></li>)}{!events.length&&<li className="p-5 text-sm text-muted-foreground">No upcoming events.</li>}</ul></Panel>
   <Panel title="Internships for you" action={<Link to="/internships" className="text-xs text-brass underline">See all</Link>}><ul className="divide-y divide-border">{recs.slice(0,3).map(i=><li key={i.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 p-4"><span><span className="block text-sm font-medium">{i.title} — {i.company}</span><span className="block text-xs text-muted-foreground">{i.location} · {i.duration}</span><span className="mt-2 flex flex-wrap gap-1.5">{(i.skills??[]).map(s=><Chip key={s}>{s}</Chip>)}</span></span><span className="text-right font-display text-xl text-success">{i.match_score}%</span></li>)}</ul></Panel>
   <Panel title="Skill breakdown" action={<Link to="/skill-profile" className="text-xs text-brass underline">Full report</Link>}><div className="space-y-4 p-5">{skills.slice(0,5).map((s,i)=><SkillBar key={s.skill_id} name={s.name} value={Number(s.score??0)} tone={i>2?"brass":"primary"}/>)}{!skills.length&&<p className="text-sm text-muted-foreground">No skills assessed yet.</p>}<Link to="/skill-assessment" className="inline-flex items-center gap-1 pt-1 text-xs text-brass underline">Take assessment <ArrowUpRight className="h-3 w-3"/></Link></div></Panel>
  </div></>}</Page>
}
