import { createFileRoute } from "@tanstack/react-router";
import { Clock, MapPin, Search, Wallet } from "lucide-react";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { Chip,Page,PageHeader } from "@/components/aicp/primitives";
import { api,type Internship } from "@/lib/api";
import { getCurrentStudentId } from "@/lib/auth";
export const Route=createFileRoute("/internships")({component:Internships});
const modes=["All modes","Remote","Hybrid","On-site"] as const;
function Internships(){const id=getCurrentStudentId();const [items,setItems]=useState<Internship[]>([]);const [apps,setApps]=useState<any[]>([]);const [query,setQuery]=useState("");const [mode,setMode]=useState<(typeof modes)[number]>("All modes");
useEffect(()=>{Promise.all([api.internships(id??undefined),id?api.applications(id):Promise.resolve([])]).then(([i,a])=>{setItems(i);setApps(a)}).catch(e=>toast.error(e.message))},[id]);
const applied=new Set(apps.map(a=>a.internship_id));const list=items.filter(i=>{const q=query.toLowerCase().trim();return(!q||i.title.toLowerCase().includes(q)||(i.company??"").toLowerCase().includes(q)||(i.skills??[]).some(s=>s.toLowerCase().includes(q)))&&(mode==="All modes"||i.mode===mode)});
return <Page><PageHeader title="Internship Marketplace" subtitle="Industry opportunities matched to your skills and profile."/><div className="mb-6 grid gap-3 rounded-lg border border-border bg-card p-4 lg:grid-cols-[minmax(0,1fr)_auto]"><div className="relative"><Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search role, company or skill" className="w-full rounded border border-input bg-background py-2.5 pl-9 pr-3 text-sm"/></div><div className="flex flex-wrap gap-2">{modes.map(m=><button key={m} onClick={()=>setMode(m)} className={`rounded border px-3 py-1.5 text-xs ${mode===m?"border-primary bg-primary text-primary-foreground":"border-border"}`}>{m}</button>)}</div></div><p className="mb-4 text-xs text-muted-foreground">{list.length} openings found</p><div className="space-y-4">{list.map(i=>{const isApplied=applied.has(i.id);return <article key={i.id} className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div><h2 className="text-base">{i.title}</h2><p className="text-sm text-muted-foreground">{i.company}</p></div><span className="font-display text-xl text-success">{i.match_score??0}%<small className="block text-[10px] text-muted-foreground">match</small></span></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex gap-1"><MapPin className="h-3.5 w-3.5"/>{i.location??"—"}</span><span className="flex gap-1"><Clock className="h-3.5 w-3.5"/>{i.duration??"—"}</span><span className="flex gap-1"><Wallet className="h-3.5 w-3.5"/>{i.stipend??"—"}</span></div><p className="mt-4 text-sm text-muted-foreground">{i.description??"Industry internship opportunity."}</p><div className="mt-4 flex flex-wrap gap-1.5">{(i.skills??[]).map(s=><Chip key={s}>{s}</Chip>)}</div><button disabled={!id||isApplied} onClick={()=>{if(!id)return;api.apply(id,i.id).then(a=>{setApps(v=>[a,...v]);toast.success("Application submitted")}).catch(e=>toast.error(e.message))}} className="mt-5 rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:bg-secondary disabled:text-muted-foreground">{isApplied?"Applied":"Apply now"}</button></article>})}</div></Page>}
