import { createFileRoute } from "@tanstack/react-router";
import { BadgeCheck,Banknote,MapPin,Search } from "lucide-react";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { Chip,Page,PageHeader } from "@/components/aicp/primitives";
import { api,type Internship } from "@/lib/api";
import { getCurrentStudentId } from "@/lib/auth";
export const Route=createFileRoute("/jobs")({component:Jobs});
function Jobs(){const id=getCurrentStudentId();const [jobs,setJobs]=useState<Internship[]>([]);const [apps,setApps]=useState<any[]>([]);const [query,setQuery]=useState("");useEffect(()=>{Promise.all([api.internships(id??undefined),id?api.applications(id):Promise.resolve([])]).then(([j,a])=>{setJobs(j);setApps(a)}).catch(e=>toast.error(e.message))},[id]);const applied=new Set(apps.map(a=>a.internship_id));const list=jobs.filter(j=>{const q=query.toLowerCase();return !q||j.title.toLowerCase().includes(q)||(j.company??"").toLowerCase().includes(q)});return <Page><PageHeader title="Jobs & Placement Marketplace" subtitle="Industry roles available through the ByteBrains ecosystem."/><div className="mb-6 rounded-lg border border-border bg-card p-4"><div className="relative"><Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by role or company" className="w-full rounded border border-input bg-background py-2.5 pl-9 pr-3 text-sm"/></div></div><p className="mb-4 text-xs text-muted-foreground">{list.length} openings found</p><div className="space-y-4">{list.map(j=><article key={j.id} className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="flex justify-between gap-4"><div><h2 className="text-base">{j.title}</h2><p className="text-sm text-muted-foreground">{j.company}</p></div><Chip tone={applied.has(j.id)?"success":"muted"}>{applied.has(j.id)?"Applied":"Not applied"}</Chip></div><div className="mt-4 flex flex-wrap gap-5 text-xs text-muted-foreground"><span className="flex gap-1"><MapPin className="h-3.5 w-3.5"/>{j.location??"—"}</span><span className="flex gap-1"><Banknote className="h-3.5 w-3.5"/>{j.stipend??"—"}</span><span className="flex gap-1"><BadgeCheck className="h-3.5 w-3.5"/>Open</span></div><div className="mt-4 flex flex-wrap gap-1.5">{(j.skills??[]).map(s=><Chip key={s}>{s}</Chip>)}</div><button disabled={!id||applied.has(j.id)} onClick={()=>{if(!id)return;api.apply(id,j.id).then(a=>{setApps(v=>[a,...v]);toast.success("Application submitted")}).catch(e=>toast.error(e.message))}} className="mt-5 rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:bg-secondary disabled:text-muted-foreground">{applied.has(j.id)?"Application in progress":"Apply now"}</button></article>)}</div></Page>}
