import { createFileRoute } from "@tanstack/react-router";
import { Clock,Lightbulb } from "lucide-react";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { Chip,Page,PageHeader } from "@/components/aicp/primitives";
import { api,type Course } from "@/lib/api";
export const Route=createFileRoute("/learning")({component:Learning});
const filters=["All","Beginner","Intermediate","Advanced"] as const;
function Learning(){const [level,setLevel]=useState<(typeof filters)[number]>("All");const [courses,setCourses]=useState<Course[]>([]);useEffect(()=>{api.courses().then(setCourses).catch(e=>toast.error(e.message))},[]);const list=courses.filter(c=>level==="All"||c.level===level);return <Page><PageHeader title="Learning Recommendations" subtitle="Courses available to close skill gaps and strengthen your placement profile."/><div className="mb-6 flex flex-wrap gap-2">{filters.map(f=><button key={f} onClick={()=>setLevel(f)} className={`rounded border px-3 py-1.5 text-xs ${level===f?"border-primary bg-primary text-primary-foreground":"border-border bg-card"}`}>{f}</button>)}</div><div className="grid gap-4 lg:grid-cols-2">{list.map(c=><article key={c.id} className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="flex justify-between gap-3"><div><h2 className="text-base">{c.title}</h2><p className="mt-1 text-xs text-muted-foreground">{c.provider??"ByteBrains Academy"}</p></div><Chip tone="brass">{c.level??"All levels"}</Chip></div><p className="mt-3 flex gap-1 text-xs text-muted-foreground"><Clock className="h-3.5 w-3.5"/>{c.duration??"Self paced"}</p><p className="mt-4 flex gap-2 rounded border border-brass/30 bg-brass/5 p-3 text-xs text-muted-foreground"><Lightbulb className="h-3.5 w-3.5 text-brass"/>{c.description??"Recommended learning resource."}</p><button onClick={()=>{if(c.course_url)window.open(c.course_url,"_blank");else toast.success(`${c.title} opened`)}} className="mt-5 w-full rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">{c.course_url?"Open course":"View course"}</button></article>)}{!list.length&&<p className="text-sm text-muted-foreground">No courses available yet.</p>}</div></Page>}
