import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Chip, Page, PageHeader, Panel, SkillBar, StatCard } from "@/components/aicp/primitives";
import { api } from "@/lib/api";
import { getCurrentStudentId } from "@/lib/auth";
export const Route=createFileRoute("/skill-profile")({component:SkillProfile});
function SkillProfile(){const id=getCurrentStudentId(); const [data,setData]=useState<any>(null); useEffect(()=>{if(id)api.skillProfile(id).then(setData).catch(e=>toast.error(e.message))},[id]); const skills=data?.skills??[]; const gaps=data?.gaps??[]; const strengths=skills.filter((s:any)=>Number(s.score)>=75).map((s:any)=>s.name); return <Page><PageHeader title="Skill Profile & Gap Analysis" subtitle="A consolidated view of your assessed skills and the gaps that matter for placements."/>{!id?<p className="text-sm text-muted-foreground">Sign in to view your profile.</p>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Overall Skill Score" value={String(data?.overall??0)} suffix="/100" note="Based on assessments"/><StatCard label="Technical Average" value={String(data?.technical_average??0)} suffix="%" note="Assessed technical skills"/><StatCard label="Soft Skills Average" value={String(data?.soft_average??0)} suffix="%" note="Assessed soft skills"/><StatCard label="Skill Gaps" value={String(gaps.length)} note="Need improvement"/></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><Panel title="Your skills"><div className="space-y-5 p-5">{skills.map((s:any)=><SkillBar key={s.skill_id} name={s.name} value={Number(s.score??0)} right={<span className="flex items-center gap-2"><Chip>{s.proficiency??"Not assessed"}</Chip>{Math.round(Number(s.score??0))}%</span>}/>)}{!skills.length&&<p className="text-sm text-muted-foreground">Take an assessment to build your skill profile.</p>}</div></Panel><Panel title="Skill gaps" action={<Link to="/learning" className="text-xs text-brass underline">See learning plan</Link>}><ul className="divide-y divide-border">{gaps.map((g:any)=><li key={g.skill} className="p-4"><div className="flex justify-between gap-3 text-sm"><span className="font-medium">{g.skill}</span><span className="text-xs text-muted-foreground">{g.current}% → target {g.target}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-accent"><div className="h-full rounded bg-primary" style={{width:`${g.current}%`}}/></div><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><TrendingUp className="h-3 w-3"/>Improve this skill</p></li>)}{!gaps.length&&<li className="p-5 text-sm text-muted-foreground">No current skill gaps. Keep learning and reassess regularly.</li>}</ul></Panel><Panel title="Strengths"><ul className="divide-y divide-border">{strengths.map((s:string)=><li key={s} className="flex items-center gap-3 p-4 text-sm"><Check className="h-4 w-4 text-success"/>{s}</li>)}{!strengths.length&&<li className="p-5 text-sm text-muted-foreground">Complete assessments to identify strengths.</li>}</ul></Panel></div></>}</Page>}
