/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SkillAssessmentRouteImport } from './routes/skill-assessment'
import { Route as SkillProfileRouteImport } from './routes/skill-profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillAssessmentRoute = SkillAssessmentRouteImport.update({
  id: '/skill-assessment',
  path: '/skill-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillProfileRoute = SkillProfileRouteImport.update({
  id: '/skill-profile',
  path: '/skill-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internships': typeof InternshipsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/skill-assessment': typeof SkillAssessmentRoute
  '/skill-profile': typeof SkillProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internships': typeof InternshipsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/skill-assessment': typeof SkillAssessmentRoute
  '/skill-profile': typeof SkillProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internships': typeof InternshipsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/skill-assessment': typeof SkillAssessmentRoute
  '/skill-profile': typeof SkillProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/internships'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/resume'
    | '/skill-assessment'
    | '/skill-profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/internships'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/resume'
    | '/skill-assessment'
    | '/skill-profile'
  id:
    | '__root__'
    | '/'
    | '/internships'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/resume'
    | '/skill-assessment'
    | '/skill-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternshipsRoute: typeof InternshipsRoute
  JobsRoute: typeof JobsRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  RegisterRoute: typeof RegisterRoute
  ResumeRoute: typeof ResumeRoute
  SkillAssessmentRoute: typeof SkillAssessmentRoute
  SkillProfileRoute: typeof SkillProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-assessment': {
      id: '/skill-assessment'
      path: '/skill-assessment'
      fullPath: '/skill-assessment'
      preLoaderRoute: typeof SkillAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-profile': {
      id: '/skill-profile'
      path: '/skill-profile'
      fullPath: '/skill-profile'
      preLoaderRoute: typeof SkillProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternshipsRoute: InternshipsRoute,
  JobsRoute: JobsRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  RegisterRoute: RegisterRoute,
  ResumeRoute: ResumeRoute,
  SkillAssessmentRoute: SkillAssessmentRoute,
  SkillProfileRoute: SkillProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
